### ISSUE TITLE
pull-to-refresh not appears when I test on Android Galaxy S5 (android 4.1.2)

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#11]
It works on iPod 5.1

**Comment by elbidone** [comment]
1. we can test following pull request:
https://github.com/mgcrea/angular-pull-to-refresh/pull/13
2. replace module to Xpull jQuery plugin for iOS and Android. Xpull is also easy to use as Angular directive
https://github.com/sjovanovic/xpull
3. if none works fine, replace pul-to-refresh to icon/link "reload"

**Comment by vanlopes** [comment]
Testing [xpull](https://github.com/sjovanovic/xpull) on project, following the README.md file on the component.

**Comment by vanlopes** [comment]
Xpull did not work on the project. Using the third way, in the **list.html**, a `div content-for` to be created to put the reload button (using the reload icon on FontAwesome) on the ActionBar.
