### ISSUE TITLE
when offline pull-to-refresh should open a toast to inform that no sync is available

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#12]

**Comment by vanlopes** [comment]
In **meumobi-sync.js** file, the `get` method has the conditional to discover if the device is online on line *10*. In that conditional, a toast should be implemented to inform the user of no connections available to sync. 
Furthermore, related to #11, it has been discovered that the `callback` function is called two times if there's a connection. One if it has or not a list of items on `localStorage` (see lines *11* and *16*) and the second one on the `list` method (when the list is retrieved from the server). This could cause performance and security problems on the app. This logic must be resolved to grant full functionality on this issue.
