### ISSUE TITLE
Badge should be erased each time SyncNews finish 

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#14]
on current version it is only erased when we relaunch App

**Comment by vanlopes** [comment]
Adding `setApplicationIconBadgeNumber(0)` on `SyncNews` function in **meumobi-sync.js** should solve the problem.

**Comment by elbidone** [comment]
Previous Fix raises following error on chrome:
TypeError: Cannot read property 'pushNotification' of undefined

You should test if window.plugins exists before "var push = window.plugins.pushNotification;" and wait deviceReady on App

**Comment by vanlopes** [comment]
in **meumobi-app.js** in the `AppFunc` factory a new function it will be created to erase notifications. It will have a `deviceReady` event and the conditional if the notification plugin is supported.
