### ISSUE TITLE
Coding Rule: Define 1 component per file

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#22]
https://github.com/johnpapa/angular-styleguide#style-y001

**Comment by vanlopes** [comment]
This [link](http://toddmotto.com/minimal-angular-module-syntax-approach-using-an-iife/) gives more detailed explanation of the IIFE rule.

**Comment by elbidone** [comment]
yes but this issue not concerns IIFE but the 1 component per file

2015-03-30 17:59 GMT-03:00 vanlopes <notifications@github.com>:

> This link
> <http://toddmotto.com/minimal-angular-module-syntax-approach-using-an-iife/>
> gives more detailed explanation of the IIFE rule.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/meumobi/infobox/issues/22#issuecomment-87829812>.
>



-- 
Dias Victor

victor.dias@meumobi.com
skype : victor.dias.meumobi

Brésil : +55 21 98348 7230
France : +33 (0)970 406 968

FAX : +33 4 26 99 94 89
