### ISSUE TITLE
app.service.* is duplicated on meumobi-app.js

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#25]
There is
```js
var app = {
    service:
...
```

and 

```js
app.service = {
        Device:
```

**Comment by vanlopes** [comment]
When the app is opened for the first time (on login page), the `LoginController` controller discovers if it is the first connection of the app on device on line *15*. This throws an error, because the event `deviceReady` is not fired yet (and so the AppInfo.service.Device still does not exist).

**Comment by vanlopes** [comment]
For a thread-safe operation, the app.service is created before cordova to initialize because of the ```isFirstConnection``` function that needs to know if the app is running for the first time.
