### ISSUE TITLE
HAL migration API

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#36]
This feature enables the [HATEOAS](http://en.wikipedia.org/wiki/HATEOAS) constraint in our REST API. This means that we'll drive the API clients through links instead of relying on them knowing our URL structure beforehand.

We'll be using the [HAL](http://stateless.co/hal_specification.html) hypermedia type, since it already has libraries in many languages that we can use. For JavaScript, we can use something like [hyperagent.js](http://weluse.github.io/hyperagent/), though I have no strong preference. Use whatever works best.

The current API actions will be left mostly unchanged for the moment, with the exception of adding a _links key for every one of them. They'll be used to drive the new clients, and this strategy will leave old clients (the ones that know about the URL structure beforehand) unchanged.

```json
    GET /api
    {
        "_links": {
            "visitor.login": {
                "href": "/api/visitors/login"
            }
        }
    }

    POST /api/visitors/login
    {
        "_links": {
            "site": {
                "href": "/api/example.meumobi.com/performance"
            }
        }
    }
```

Some docs about Hyperclient:

- http://weluse.github.io/hyperagent/
- http://stateless.co/hal_specification.html

**Comment by elbidone** [comment]
The README of [URI.js] provide a way to include it on project through npm (cf package.json). If think cleaner to use it instead of src from bower.

[URI.js]: https://github.com/medialize/URI.js/

**Comment by vanlopes** [comment]
Using **hyperagent.js**, the `POST` test is made in **meumobi-api.js** at line *69*.
However, it seems that this library couldn't handle the method responses (if POST was successful or not), because then function is not triggered.

To know if the result was succesful outside the app, [this link](http://weluse.github.io/hyperagent/sample/) lists the users created. Every user with "by IM" on the post was created by the application.

**Comment by vanlopes** [comment]
It is decided that we won't use HAL components in this project because it is only useful when the user is logged in. We'll use the default $http component instead to fetch the user's settings and the site paths.

**Comment by elbidone** [comment]
This commit was not tested correctly. It raises following error:
**TypeError: Cannot read property 'DOMAIN' of undefined**
raised on:
```js
...
if (response && response.status === 401) {
	delete localStorage.user;
	delete localStorage.site;
	$rootScope.site = SITE.DOMAIN;
	$rootScope.go('/login');
}
...
```

**Comment by vanlopes** [comment]
In **meumobi-api.js**, on the factory `errorInterceptor`, the variable `SITE` is undefined. When I instantiate `meumobi.settings` on the factory, it gives me `Unknown Provider` error:

```js
(...)
.factory('errorInterceptor', ['$q','meumobi.settings', '$rootScope', '$location',
function($q, $rootScope, $location, SITE) {
	return {
		request: function(config) {
			$rootScope.$broadcast('loading:show');
			return config || $q.when(config);
		}(...)
```
```error
Uncaught Error: [$injector:unpr] Unknown provider: meumobi.settingsProvider <- meumobi.settings <- errorInterceptor <- $http <- $templateRequest <- $compile <- CaptureService
```

**Comment by vanlopes** [comment]
Created ```$rootScope.defaultSite``` to have a default site API to make requests.
