### ISSUE TITLE
forgot form should prevent to submit with empty mail

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#54]
See #46 for details about how to achieve it

**Comment by vanlopes** [comment]
Using "Only Showing Errors After Submitting the Form" way on https://scotch.io/tutorials/angularjs-form-validation

**Comment by elbidone** [comment]
A lot of bugs have been introduced with this commit. All of them due to bad copy/paste or because you've decided to not follow the example provided.
- bad check on ng-show, because error msg is always display, even if the user didn't modify the form ($pristine)
```js
// WRONG code, always TRUE if user don't modify
ng-show="forgotForm.email.$invalid || forgotForm.email.$pristine"
// RIGHT code (same used on example provided)
ng-show="forgotForm.email.$invalid && !forgotForm.email.$pristine"
```
- you use forgotForm.email.length but never set the minlength required
- you use help-block class but without .has-error class it will have no effect
- I don't understand the use of  

> class="ng-pristine ng-valid ng-valid-email ng-submitted", if these class are automatically setted by angular
