### ISSUE TITLE
update One Time Password management

### ISSUE THREAD

**Issue by elbidone** [meumobi/infobox#8]
Now, when POSTing to /visitors/login and the visitor has should_renew_password == true, the api returns "error" => "password expired", like so:

{"token":"dbea997b978117fdbf91ff35721f2c37f88fd7f7","visitor":{"email":"juliogreff@gmail.com"},"error":"password expired"}

Furthermore, the only endpoint that would be allowed is PUT /visitors. This should allow the visitor to update his password. That will set should_renew_password to false, and allow all endpoints again.

**Comment by vanlopes** [comment]
In **login_controller.js** on line *67*, ``` if (resp.visitor.should_renew_password)``` will be changed due to changes of the login response to ``ìf(resp.error && resp.error == "password expired")```.
